### ISSUE TITLE
Problem with the MUSTACHE_TEMPLATES object

### ISSUE THREAD

**Issue by Silverdust-ZH** [julienba/play2-mustache#11]
Hie Julien
I am thankfully using your plugin and it works great - as long as I keep all templates in one singe folder and avoid any nesting. As soon as I start to organize my templates in subfolders, the content of the object MUSTACHE_TEMPLATES seems rather weird:

mustache/account/filter => mustacheaccountfilter
mustache/filter/standard => mustacheilterstandard (missing f of filter)
mustache/rating/add => mustacheatingadd (missing r of rating)

As soon as I copy to the production server (linux) from my development system (windows) none of the templates work anymore because the content of MUSTACHE_TEMPLATE has some different values in there, thus no template is beeing found anymore.

Best regards
Samuel

**Comment by julienba** [comment]
Which version are you using ?

**Comment by Silverdust-ZH** [comment]
Hi Julien thanks for replying :-)
It's Version 1.1.2

Id love to access the templates using the web path separator (forward slash), i. e. mustache/rating/add for example, making no difference between windows and linux systems. All other paths in the web app are also using forward slashes independant of the environment system. ;-)

**Comment by julienba** [comment]
It's 1.1.2 in Build.scala and plugins.sbt ?
Are you using play 2.1 ?

i just checked the sample application and that work for me

**Comment by Silverdust-ZH** [comment]
Yes, its defined this way in both locations and yes, I am using play 2.1.
I attaches two screenshots, one shows a sample from the folder structure and the other what I get at runtime
![mustache](https://f.cloud.github.com/assets/4924612/743002/cff28922-e3dd-11e2-8cb9-05c073dcb372.png)
![structure](https://f.cloud.github.com/assets/4924612/743003/cff615c4-e3dd-11e2-97d7-65721e53328b.png)

**Comment by julienba** [comment]
probably a windows issue
what do you have in http://localhost:9000/assets/javascripts/mustache-tmpl.js in you windows machine ?

On linux you sould have something like filter/coaches.
The problem is probably located here: https://github.com/julienba/play2-mustache/blob/master/src/main/scala/org/jba/SbtMustachePlugin.scala#L67 if you want to fix this yourself

I'll investigated quickly this when I have found a windows

**Comment by Silverdust-ZH** [comment]
var MUSTACHE_TEMPLATES={'mustache\account\login'...
It makes sense to me now. He probably uses an environment sensitive path separator causing sequences like \a \r \f. \a seems to be ignored, since its no valid escape sequence. Howerver \r and \f are beeing interpreted somehow. Wow, it looks like it is as well depending on the enviroment system on the serverside and the browser on the client side - as different javascript engines might treat escape sequences as hash keys differently.

We do somehow have to get rid of the context sensitive path separator, when composing the key for the hashtable. Use it for reading the file system but then statically put a forward slash when composing the key.

If you like, I can change it for you but probably not before tomorrow as I am really get overwhelmed by work here right now :-/

**Comment by Silverdust-ZH** [comment]
I am gonna fix the problem now ;-)

**Comment by julienba** [comment]
Can you try the sbt plugin 1.1.3-SNAPSHOT please ?

I can't find a windows that works properly ...
