### ISSUE TITLE
Mandatory app restart for updated mustache templates when rendered on server

### ISSUE THREAD

**Issue by ghost** [julienba/play2-mustache#16]
Line 64 of Mustache.scala:

val input = Play.current.resourceAsStream(rootPath + resourceName  + ".html").getOrElse(throw new Exception("mustache: could not find template: " + resourceName))

The classloader is not aware of any Mustache template changes and so reloads the stale file. Not sure if a listener could be added to update the classloader, or if it is better to retrieve the file in some other manner, at least for non-prod environments.

**Comment by julienba** [comment]
What do you mean by "on server" ?

In dev mode all the files should be automatically reload. This is not the case for you ?

**Comment by ghost** [comment]
While developing in a non-prod mode, we've found that when we modify a mustache template and then render that template on the server, versus using client-side rendering, the most recent changes to the mustache template aren't reflected unless we restart Play. I assume that the file resolved is not updated because the classloader isn't listening for the changes.

**Comment by ghost** [comment]
If you're seeing these files reloaded for you then perhaps we've misconfigured something?

**Comment by julienba** [comment]
I just tried with the sample project and that's work for me. 
Maybe your template are not in the assets/mustache folder ?

**Comment by ghost** [comment]
I think you're right. We shift our mustache templates to a public dir, so I will look into this and get back to you.
