### ISSUE TITLE
why Template not found?

### ISSUE THREAD

**Issue by mfirry** [julienba/play2-mustache#7]
i've got a simple 

``` java
public static Result index() {
String message = "hello";
return ok(index.render(message));
}
```

i've got index.scala.html

with 

```
@(message: String = "hello")

@import org.jba.Mustache

@Mustache.render("index", message)
```

then app/assets/mustache/index.html with

```
<div class="span6">
<h1>{{> home-title}}</h1>
</div>
```

and app/assets/mustache/home-title.html with some simple html

and i get

[[UncheckedExecutionException: com.github.mustachejava.MustacheException: Template home-title not found]]

what am i doing wrong?

**Comment by julienba** [comment]
{{> home-title}} call the partial template home-title

see: http://mustache.github.com/mustache.5.html

**Comment by mfirry** [comment]
i don't think i'm following you

**Comment by julienba** [comment]
currently partial does not work, try without.
Remove ">"

**Comment by julienba** [comment]
Partial should work now with version: "org.jba" %% "play2-mustache" % "1.0.1"
