### ISSUE TITLE
Support for Play2.1?

### ISSUE THREAD

**Issue by shirishp** [julienba/play2-mustache#8]
Please add support for Play2.1

**Comment by julienba** [comment]
Done for 2.1-RC1. It's on branch 2.1 if you would modify some things

**Comment by ghost** [comment]
What do you mean by "modify some things"?

**Comment by julienba** [comment]
if you would read the source and contribute, it's not on the master branch, because sbt plugin for play have slightly different API between 2.0 and 2.1. And 2.1 is not yet a final release.

**Comment by ghost** [comment]
I will see what I can do.

Thanks,
nathan

**Comment by rssh** [comment]
see https://github.com/julienba/play2-mustache/pull/9

**Comment by julienba** [comment]
Thanks, it's merge. 
I also added one fix for partial templating

**Comment by shirishp** [comment]
Thank you very much. :)

With regards,
Shirish Padalkar
http://twitter.com/_Garbage_
